apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-validation-controller
spec:
  selector:
    matchLabels:
      app: basic-validation-controller
  template:
    metadata:
      labels:
        app: basic-validation-controller
    spec:
      volumes:
        - name: certs
          secret:
            secretName: webhook-tls-certs

      containers:
        - name: basic-validation-controller
          image: sachinnicky/basic-validation-controller
          imagePullPolicy: IfNotPresent
          env:
            - name: WHITELISTED_REGISTRIES
              value: "docker.io,gcr.io"
          volumeMounts:
            - mountPath: /certs
              name: certs
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: basic-validation-controller
spec:
  selector:
    app: basic-validation-controller
  ports:
    - port: 443
      targetPort: 8443
