apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: basic-validation-controller
webhooks:
  - name: basic-validation-controller.default.svc.cluster.local
    clientConfig:
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURZRENDQWtpZ0F3SUJBZ0lVRitlL3BYd1FiM1BRZ25RdmJ1NjNRcDJ6UUhVd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0tURW5NQ1VHQTFVRUF3d2VZbUZ6YVdNdGRtRnNhV1JoZEdsdmJpMWpiMjUwY205c2JHVnlYMk5oTUNBWApEVEl4TURReU1URTNNVGswTTFvWUR6SXlPVFV3TWpBME1UY3hPVFF6V2pBcE1TY3dKUVlEVlFRRERCNWlZWE5wCll5MTJZV3hwWkdGMGFXOXVMV052Ym5SeWIyeHNaWEpmWTJFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFEZVcvQ2g4Z3AvaGVlaDlQWVFidVRUUkExRjYweVpRL25LUk1lMjFBRnBCdWVtaCtqYwpnbzFJcGp5aE9wSkVhOG1pN0xPQkdoQlVDb2JSRUZiNW1ycFJJUjBXaUNvck9Wb0Ywc25rQ3VzcGZ4L3NRQWhZCkI5b1d5dERUNTA4TmtxdkVLVTRDL1YxK0tQTmU0SDVWck1KZy9RSEIzNDhqMU04VHZwQnpiT3NVTXhEUVh6QTQKcTU5T25rNGV1SjFoYzJiNTl4YkFoSUdUREZBNDBBb2xFS2c0eHd2aGpINXJKdzk3S0tsTGxqTW9aWVdweUl2bQprZFR5L2xidVRwUnBGQ0hma01YcW5seGRTdnhPZVFjUkw0a2o4R0tyejh5T04yS3JqUzBjU2FWR2hVL2Q2dVpWCnJUcTNYdGFGUTh0VVVoSExsTFNjZ05OdHNVK3d4YkNSS3F1VEFnTUJBQUdqZmpCOE1CMEdBMVVkRGdRV0JCVFEKZnpUOUIyeUg0cklKVmVOT2FRM0V5Z01udlRBZkJnTlZIU01FR0RBV2dCVFFmelQ5QjJ5SDRySUpWZU5PYVEzRQp5Z01udlRBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUNrR0ExVWRFUVFpTUNDQ0htSmhjMmxqTFhaaGJHbGtZWFJwCmIyNHRZMjl1ZEhKdmJHeGxjbDlqWVRBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQUtwN2pBampOSTdKZ3dkckUKQ1Vic0lweTJYM3h0MXMzZ0gybi9EWUR5YlVrWDNDOWNqSUd0Q0pwdW1CaTRTVkZOOVcwM2diR0RYeWZUSDhIVQpHRExQT2UxSUw0WWova2FRRllEV29EbTdTZTdKNXI0OVVmanVaek9hN3JIczRrOWtmck1CZm90WXZiZ00zZzAwCllKQ20rakZ4cW12Wmp6ejlUaEM3TFFLaWFvOFhiVzFXaW1HOTBKMkVNbEl1VmI0ZUVDa1VmVjNnK2pmVXQ5VjIKZFJoUnZvK0YzN3MyZmpJL3hjY2NGaUtGRXN1QVhOdDdwbE9HVHdTOG1kUU5rai9NM3c4TUJIblVHWTFhTWoxZwpHMEJIRzMzOEJOcUxQR3U0WUVkTitNVGtVZEp5VDhlbzBSTVVuRnpIOVgwQWZ5Z21EM2ZrNlM2RGhpSHlKVXJiCk1WSC9aZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
      service:
        name: basic-validation-controller
        namespace: default
        port: 443
        path: "/mutate"
    failurePolicy: Ignore
    rules:
      - operations:
          - "CREATE"
        apiGroups:
          - ""
        apiVersions:
          - "v1"
        resources:
          - "pods"
    sideEffects: None
    admissionReviewVersions: ["v1beta1", "v1"]
