apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: basic-validation-controller
webhooks:
  - name: basic-validation-controller.default.svc.cluster.local
    clientConfig:
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURZRENDQWtpZ0F3SUJBZ0lVYjFXYVd5N0VXTmFHSTJMamJmL24vblZhbGprd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0tURW5NQ1VHQTFVRUF3d2VZbUZ6YVdNdGRtRnNhV1JoZEdsdmJpMWpiMjUwY205c2JHVnlYMk5oTUNBWApEVEl4TURReE9UQTNNak0wT1ZvWUR6SXlPVFV3TWpBeU1EY3lNelE1V2pBcE1TY3dKUVlEVlFRRERCNWlZWE5wCll5MTJZV3hwWkdGMGFXOXVMV052Ym5SeWIyeHNaWEpmWTJFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDbDNaNDJtUW1XMkpCV2dxV0xoTUx0SjFXSVFXOHZMVzc1NG1UR1ZNTE5OT28wbGhrLwo0ZW43SGhKVXZWdWtWcU5WbFQ5TkJkRDRhVkpRbTRmVGRxdUk3Z005UWQ0bVp2R2NNSzBnQ0UzdVYrODNCNlFPCm5IR3ZxdklUSVVQcVFDOGE3ZkxST055dnlBQ3pTcnVjbzF2WDhONEdTUURGeEc0Qld2NDBEQ1BvUXY0ZmtOZ3AKQy9ZeE5lNW9XWVo1dUxRdDZqVUxyUzJ3aVZYWXRCZ09jYUhoNnI0anRnaUpjS1NNU2RPdjhCS0pObHpsUGdGcApxSzk4VVA2bEhib2dabXMzNk0zTHpxak1ERXVzSWtYVUtxUGRvRFQrSHg4RXN4VnR3a0ZyaVB5UUcvS3VmY1BjCkpLdGZia3dDTzQzWEVsbjRMN3JUbUlsMi9JVkZZb0wzLzJEZkFnTUJBQUdqZmpCOE1CMEdBMVVkRGdRV0JCUzIKZDgzYzdBcS9KODNZMlF0cmhkS0JNaUNEZ0RBZkJnTlZIU01FR0RBV2dCUzJkODNjN0FxL0o4M1kyUXRyaGRLQgpNaUNEZ0RBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUNrR0ExVWRFUVFpTUNDQ0htSmhjMmxqTFhaaGJHbGtZWFJwCmIyNHRZMjl1ZEhKdmJHeGxjbDlqWVRBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQUNKTUdiZENzbDMvRk50djcKUC9aWW92S2IwNDlKWFVDZU1RTkY2enNxZC9FNjZkd2wveDZiNmh0MjJVazBRU0NURVZmR2xIMjM1bk1JcEVqQQorVEhmOHdrOEU2bmRZQ0JMRGNWWGNkUGxrWDc5enZsSCtWQnBtRmJQdEVCVWFGOWcyNFgvTEFFT1dCclJVN0V1Clc0RmtROVFCaGRnWjhOWkNnZXBSeHF6V2VLeFp5eFFRQ3g3Ny9ZaHNKM0JqWEF0Q3NBcXZqNUh4cE9UejQzdFQKblJ0MlIxd0dzSmY1QS91cGlwWWt0TDc2MEMrc0tYZmlnV1pmbDV4WThHeDZJSWwrR00xY0JCdDVSTHNhREZSdApZU1RIL3ZXd0puNzBCVXhuTGRtQ1hzYjIrd2NmYTJZQjk0c1Fza1hEWmc4aXlja0NRa2lQWnNSQWl4Zk9GQnppCnFSZHRxUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
      service:
        name: basic-validation-controller
        namespace: default
        port: 443
        path: "/mutate"
    failurePolicy: Ignore
    rules:
      - operations:
          - "CREATE"
        apiGroups:
          - ""
        apiVersions:
          - "v1"
        resources:
          - "pods"
    sideEffects: None
    admissionReviewVersions: ["v1beta1", "v1"]
